--- Makefile.orig	2017-02-04 13:16:00.000000000 -0600
+++ Makefile	2017-03-14 00:00:00.000000000 -0500
@@ -10,7 +10,7 @@
 	sed \
 		-e '\#^\. .*/common"# {' -e 'r bin/common' -e 'd' -e '};' \
 		-e 's/^VERSION=.*$$/VERSION="${DEB_VERSION}"/;' \
-		$^ > $@
+		$< > $@
 
 install:
 	install -d ${DESTDIR}/${bindir} ${DESTDIR}/${examplesdir}
