Index: cereal-0.15/Makefile
===================================================================
--- cereal-0.15.orig/Makefile	2007-11-26 15:37:06.000000000 -0500
+++ cereal-0.15/Makefile	2007-11-26 15:38:01.000000000 -0500
@@ -21,9 +21,11 @@
 	install fs/usr/sbin/cereal-admin $(PREFIX)/sbin/cereal-admin
 	install -m 0644 fs/usr/share/man/man1/cereal.1 $(PREFIX)/share/man/man1/cereal.1
 	install -m 0644 fs/usr/share/man/man8/cereal-admin.8 $(PREFIX)/share/man/man8/cereal-admin.8
-	install fs/usr/share/cereal/{log,main}run $(PREFIX)/share/cereal/
+	install fs/usr/share/cereal/logrun $(PREFIX)/share/cereal/
+	install fs/usr/share/cereal/mainrun $(PREFIX)/share/cereal/
 	install -m 0644 fs/usr/share/cereal/common $(PREFIX)/share/cereal/
-	install -m 0644 fs/etc/cereal/{cereal-admin.conf,screenrc} $(CONFIGDIR)/cereal/
+	install -m 0644 fs/etc/cereal/screenrc $(CONFIGDIR)/cereal/
+	install -m 0644 fs/etc/cereal/cereal-admin.conf $(CONFIGDIR)/cereal/
 
 # invoke this target like `make VERSION=0.1 release' to build an
 # "upstream tarball".
